import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import net from 'node:net';
import {openRpcTimingProxy} from './rpcTiming.mjs';
async function fixture(handler){const server=http.createServer(handler);await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));return {port:server.address().port,close:()=>new Promise(resolve=>server.close(resolve))};}
async function post(port,path,body){return new Promise((resolve,reject)=>{const request=http.request({hostname:'127.0.0.1',port,path,method:'POST',headers:{'Content-Length':Buffer.byteLength(body),'Content-Type':'application/json'},agent:false},response=>{const chunks=[];response.on('data',chunk=>chunks.push(chunk));response.once('end',()=>resolve({status:response.statusCode,headers:response.headers,body:Buffer.concat(chunks)}));});request.once('error',reject);request.end(body);});}
test('proxy forwards exact bytes and reframes chunked upstream output for native sockets',async()=>{const body=' {"jsonrpc":"2.0","method":"generateblocks","params":{"amount_of_blocks":18,"wallet_address":"private-address"}} ';let forwarded;const target=await fixture((request,response)=>{const chunks=[];request.on('data',chunk=>chunks.push(chunk));request.once('end',()=>{forwarded={method:request.method,path:request.url,body:Buffer.concat(chunks).toString()};response.writeHead(200,{'Content-Type':'application/json'});response.write('{"result":');response.end('{"status":"OK"}}');});});const callback=[],proxy=await openRpcTimingProxy({targetPort:target.port,onEvent:event=>callback.push(event)});try{const answer=await post(proxy.port,'/json_rpc',body);assert.deepEqual(forwarded,{method:'POST',path:'/json_rpc',body});assert.equal(answer.body.toString(),'{"result":{"status":"OK"}}');assert.equal(answer.headers['content-length'],String(answer.body.length));assert.equal(answer.headers.connection,'close');assert.equal(answer.headers['transfer-encoding'],undefined);assert.equal(callback.length,1);assert.equal(callback[0].method,'generateblocks');assert.equal(callback[0].amount_of_blocks,18);assert.equal(callback[0].status,200);assert(!JSON.stringify(proxy.events()).includes('private-address'));}finally{await proxy.close();await target.close();}});
test('unknown routes and methods never reach upstream or enter telemetry as arbitrary strings',async()=>{let calls=0;const target=await fixture((_request,response)=>{calls++;response.end('{}');}),proxy=await openRpcTimingProxy({targetPort:target.port,maxEvents:1});try{assert.equal((await post(proxy.port,'/private-endpoint','{}')).status,403);assert.equal((await post(proxy.port,'/json_rpc','{"method":"secret-material"}')).status,403);assert.equal(calls,0);assert.equal(proxy.events().length,1);assert.equal(proxy.events()[0].method,'rejected-json-rpc');assert(!JSON.stringify(proxy.events()).includes('secret-material'));}finally{await proxy.close();await target.close();}});
test('native read-to-end sees an explicit length and connection EOF',async()=>{const target=await fixture((_request,response)=>response.end('{"status":"OK"}')),proxy=await openRpcTimingProxy({targetPort:target.port});try{const raw=await new Promise((resolve,reject)=>{const socket=net.connect(proxy.port,'127.0.0.1'),chunks=[];socket.on('data',chunk=>chunks.push(chunk));socket.once('error',reject);socket.once('end',()=>resolve(Buffer.concat(chunks).toString()));socket.once('connect',()=>socket.write('POST /get_outs HTTP/1.1\r\nHost: 127.0.0.1\r\nContent-Length: 2\r\nConnection: close\r\n\r\n{}'));});assert.match(raw,/HTTP\/1\.1 200/);assert.match(raw,/Content-Length: 15/i);assert(!/transfer-encoding/i.test(raw));assert(raw.endsWith('{"status":"OK"}'));}finally{await proxy.close();await target.close();}});
test('upstream timeout is bounded and its telemetry excludes response content',async()=>{const target=await fixture((_request,response)=>setTimeout(()=>response.end('secret-response'),100)),proxy=await openRpcTimingProxy({targetPort:target.port,timeoutMs:20});try{const answer=await post(proxy.port,'/get_transactions','{}');assert.equal(answer.status,504);assert.equal(proxy.events()[0].errorCategory,'upstream-timeout');assert(!JSON.stringify(proxy.events()).includes('secret-response'));}finally{await proxy.close();await target.close();}});
